### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jerh616** [bogg/subpipeline#1]
- [ ] Determine if we can specify a regex/folder for resources input in kustomise
- [ ] Doc how to create a .dockerconfigjson secret
- [ ] Finalise git repo(s) shape (for the output of the export)
- [ ] Export properties from existing toolchain
- [ ] Export referenced secrets from existing toolchain
- [ ] consume formatted secrets and resolve from HashiCorp using approle
- [ ] FVT
- [ ] Load/Performance Test - large number of repos, large volume of runs (is this reasonable - it's a single user, manually executing. perhaps for Q2 we worry more about call volume and post run cleanup)
